### ISSUE TITLE
setup/teardown events (mount/unmount)

### ISSUE THREAD

**Issue by sloev** [medium-tech/van-cone#1]
i figured out how to do mount/unmount events using isCurrentPage together with a component state object, in my case "cameraIsOn"

```js
 van.derive(()=>{
        if(cone.isCurrentPage("new") && !cameraIsOn.val){
            startCamera()
        }
        if(!cone.isCurrentPage("new") && cameraIsOn.val){
            stopCamera()
        }
    })
```

**Comment by b-rad-c** [comment]
We could add an `onEnter` and `onExit` hook for each route. I wouldn't think the `onEnter` would be strictly necessary because you could just run whatever initialization code you need in the function but I can see a use for the `onExit` hook. But, if we're doing `onExit` we might as well do `onEnter` for parity.

In your use case does it matter when the hooks are run in relation to the DOM being updated? For example in `onEnter` would it matter if the hook were run before the DOM was updated, after it was updated, or not important?

**Comment by sloev** [comment]
Not important, but i logically it would be before render i think
